### ISSUE TITLE
Need to have some studies about what attributes are copied by ltfs_ordered_copy

### ISSUE THREAD

**Issue by piste-jp-ibm** [LinearTapeFileSystem/ltfs#155]
**Is your feature request related to a problem? Please describe.**

At this time, I don't have any studies about what attribute is copied by `ltfs_ordered_copy` program.

It uses `shutils.copy()` by default and `shutils.copy2()` when `-p, --preserve` is specified. But there is no specification what attributes are copied exactly. 

**Describe the solution you'd like**

1. Need to study what `shutils.copy()` and `shutils.copy2()` copy to destination
2. Support same functionality of `cp -p` and `cp -a` into `ltfs_ordered_copy`

**Additional context**

May be `shutils.copy()` and `shutils.copy2()`doesn't copy extended attribute at all. Extended attribute shall be copied when `-a` option is specified.

**Comment by piste-jp-ibm** [comment]
Hi @ruixiaoLee,

Feel free to use this issue if you want to make a PR to this project.

**Comment by ruixiaoLee** [comment]
1. `cp -p` copies mode,ownership and timestamps; `cp -a` copies all the attributes including mode,ownership,timestamps,context, links, xattr(according to man page) 
2. `shutil.copy()` copies mode(permission bits)
3. `shutil.copy2()` copies mode, last access time, last modification time, and flags 
4. Neither `shutil.copy()` nor `shutil.copy2()` can copy xattr and ownership
5. Now ,`ltfs_ordered_copy -a` can copy mode,timestamps and xattr , which is slightly different from `cp -a` because ownership and links are not considered
6. Now , `ltfs_ordered_copy -p` can copy mode and timestamps which is slightly different from `cp -p` because ownership and links are not considered
######
|   | `shutil.copy()` | `shutil.copy2()` | `cp -a` | `cp -p` | `ltfs_ordered_copy -a` | `ltfs_ordered_copy -p` |
|---------------|----------------|-------|-------|----------------------|----------------------|---|
| mode          | O              | O     | O     | O                    | O                    | O |
| timestamps    | X              | O     | O     | O                    | O                    | O |
| ownership     | X              | X     | O     | O                    | X                    | X |
| xattr         | X              | X     | O     | X                    | O                    | X |
| links         | ?              | ?     | O     | X                    | ?                    | ? |

**Comment by piste-jp-ibm** [comment]
HI,

Thank you very much for your contribution. It looks great!
