### ISSUE TITLE
RFC: split write over multiple tapes

### ISSUE THREAD

**Issue by rzerres** [LinearTapeFileSystem/ltfs#170]
# The Problem: Howto control/handle write operations, that consume multiple tapes?

I need to split up a btrfs-send/btrfs-receive pipe, since data will not fit on a single tape.

# Solution proposel

LTFS should offer an api, advertising e.g.

* "no space left",
*  "<x MB> space left"

This will enable the callee to interrupt a write process without preprocessing the available free LTFS partition space.
The machanism how the EOT message is exchanged need to be discussed.

Callee needs to handle following tasks:

* Write a mark/struct/file describing the active slice/parent/sibbling

* LTO loader functions / manual operator intervention must be issued to unmount + unload the given tape

* LTO loader functions / manual operator intervention must be issued to load + mount a new tape.

* Write a mark/struct/file describing the active slice/parent/sibbling

* continue to save the data pipe

this is just a rough starter. I haven't read any available solution on how to implement this featurerequest.

Any feedback is quite welcome.

**Comment by piste-jp-ibm** [comment]
I think you can use the extended attribute, `ltfs.mediaDataPartitionAvailableSpace`.

This EA shows the remaining capacity of data area actually. You can access this EA on `user.ltfs.mediaDataPartitionAvailableSpace` by `getxattr()`. Or you can use `attr` command with `ltfs.mediaDataPartitionAvailableSpace`.

See also https://github.com/LinearTapeFileSystem/ltfs/blob/f82968d6f5cf28d6e24499fc0d400080636153a5/src/libltfs/xattr.c#L1095

**Comment by piste-jp-ibm** [comment]
Another thought is you can use the extended attribute, `ltfs.mediaDataPartitionAvailableSpace`.

This EA shows the remaining capacity of data area actually. You can access this EA on `user.ltfs.mediaDataPartitionAvailableSpace` by `getxattr()`. Or you can use `attr` command with `ltfs.mediaDataPartitionAvailableSpace`.

See also https://github.com/LinearTapeFileSystem/ltfs/blob/f82968d6f5cf28d6e24499fc0d400080636153a5/src/libltfs/xattr.c#L1095

**Comment by rzerres** [comment]
Thanks for the input.
For the backup process I'll try to calculate the needed space of given data beforehand sending it to the pipe. so roughtly

* If source-len > ltfs.mediaDataPartitionAvailableSpace (on valid LTFS volume_name)
 * breakeup the source-data; source-len_trunk_(n) <= ltfs.mediaDataPartitionAvailableSpace on active volume_name)
 * send source-len_trunk_(n) down the pipe -> save to LTFS volume_name
 * check ltfs.mediaDataPartitionAvailableSpace >= 0 (successfully stored)

* prepare new media (respect pool-membership, retension restrictions, etc for next volume_name)
  * get ltfs.mediaDataPartitionAvailableSpace on new active volume_name

* if remaining source-data-len >  ltfs.mediaDataPartitionAvailableSpace
   * breakup the remaining source-data to source-len_trunk_(n+1)  <=  ltfs.mediaDataPartitionAvailableSpace 

* save parent LTFS volume_name on active LTFS volume_name
  * send source-len_trunk_(n+1) down the pipe -> save to LTFS volume_name

**Comment by piste-jp-ibm** [comment]
I have 2 things I would like to mention about capacity.

One is capacity, the other is sync.

---
For capacity, LTFS capacity is based on the remaining capacity information returned from the drive. So you need to take care about these things.

1. The Drive (at least IBM drive) returns native capacity
2. The "native" capacity means a capacity after H/W compression
3. LTFS formats a tape with `compression on` setting by default

So you may have bigger capacity than you expect after you write compressable data to LTFS.

For example, remaining capacity is 10GB. You write a 5GB file (2:1 compressable by the drive). Remaining capacity shall be 7.5GB. 

---
For sync, I assume `incremental snapshot` you said is periodical index automatically committed by LTFS.

I recommend not to use `periodical sync` when you are using LTFS from another automated S/W. 

You can commit (write an index) when your application want to commit all data if you use LTFS with `-o sync_type=unmount` and Access to `ltfs.sync` EA.

In my sense, you can get a reliable remaining capacity if you use the following sequence

1. Check a capacity
2. Write a file or some files
3. Write anything to `ltfs.sync` EA
4. Check a capacity (This value is reliable because new index shell be written in step3)

**Comment by piste-jp-ibm** [comment]
Close this issue because we don't have any additional comment from 12/19/2019.
