### ISSUE TITLE
Monitoring TapeAlert while ltfs is active

### ISSUE THREAD

**Issue by scsirob** [LinearTapeFileSystem/ltfs#181]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'd like the ability for external software to monitor some of the tape drive's status while it's under control of LTFS. Currently this is impossible as LTFS opens the device with O_EXCL access, blocking secondary access. An API to read status of the drive without interfering with LTFS would be most elegant. I would like to be able to read the TapeAlert flags, to monitor the Eject button.

**Describe alternatives you've considered**
I reached my goal by changing the  _raw_dev_open() function in sg-ibmtape.c to drop the O_EXCL flag. That allows me to open the device a second time and issue Log Sense commands from my software while LTFS is running. LTFS is unaware of this and seems happy, but I do not know for sure if this might interfere anywhere. Potential risk right now is that LTFS or other software could be activated on the same device, so some other means of preventing double access would be needed.

**Additional context**
I am writing software that uses LTFS tapes as a repository for multiple legacy virtual tape images (www.consolitape.com). The software includes a daemon that monitors the tape drive for tapes to be inserted. When a new tape arrives, the daemon checks if it is an LTFS tape in the MAM chip, and if so, sends a Prevent Media Removal, then calls LTFS to mount the tape. If the mount succeeds, it scans the mounted tape for virtual tape images, and automatically spins up a matching Virtual tape library with Virtual drives and slots that allow read-only access to those images as if they were a real library and drives. The Virtual library is shared through iSCSI and can be accessed by preserved legacy backup applications without requiring the legacy tape hardware or tapes.

To make operator interaction easy, I monitor the TapeAlert flags for an Eject button pushed event. When detected, the Virtual library and drives are automatically taken off-line, the LTFS tape is dismounted, an Allow Media Removal is sent, and the tape is ejected. The operator does need any GUI or command line access.

**Comment by piste-jp-ibm** [comment]
I don't think it is good idea to open one device with multiple processes. I will never accept such kind of PR.

The functionality you need is already implemented by the "ltfs.mediaStorageAlert" EA.  You can try to access to teh EA with `attr` command like `$ attr -g ltfs.mediaStorageAlert [mount_point]`. 

The value is presented by the text of uint64_t like `0x0000000000000000`. The LSB shows TA1 and the MSB shows TA64. Each flag is latched when it is raised and you can clear it to write `1` to corresponding bit with `attr` command also. (Basically TA provided by the drive is read/clear, but LTFS provides latched flags because of some reasons)

For example, you can clear TA64 and TA2 with `$ attr -s ltfs.mediaStorageAlert -V 0x8000000000000002 [mount_point]`.

---
This functionality is provided by each tape backends. Please refer `struct tape_ops::get_tape_alert ()` in detail. In the sg_ibmtape backend, `sg_ibmtape_get_tape_alert()` is the actual function

**Comment by scsirob** [comment]
Excellent, thank you for your help and elaboration. I will investigate using the EA feature.

**Comment by scsirob** [comment]
Just a quick follow-up. The EA feature works as designed. It took me a while to find that inside my software I had to prepend 'user.' to the attribute, but after that
`setxattr(path, "user.ltfs.mediaStorageAlert", buffer, length, flags)` and 
`getxattr(path, "user.ltfs.mediaStorageAlert", buffer, length)` work just fine. 
My software no longer needs SCSI access while ltfs is in control. Thank you!

**Comment by piste-jp-ibm** [comment]
Great news.

The prefix thing `user.` comes from Linux spec. On Linux, user only access under `user.` area for EA (May be is is deeply related into SELinux implementation). So `user.` prefix is needed for accessing from `setxattr()` and `getxattr()` functions. On the other hand, it is not needed on macOS.
