### ISSUE TITLE
Bugs in current master

### ISSUE THREAD

**Issue by HannesRadner** [LinearTapeFileSystem/ltfs#237]
first issue
I downloaded the current master and tried to compile it for 
Kernel version: Linux version 5.10.7-gentoo (xxx@linuxServer) (gcc (Gentoo 9.3.0-r2 p4) 9.3.0, GNU ld (Gentoo 2.34 p6) 2.34.0)

it failed with

arch/arch_info.c:52:10: fatal error: sys/sysctl.h: No such file or directory
   52 | #include <sys/sysctl.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.

to make it work I changed 
52 | #include <sys/sysctl.h> to 52 | #include <linux/sysctl.h>

this seems to be necessary for new Linux builds because sys/sysctl.h has been moved to linux/sysctl.h

***
second issue
when starting ltfs the first time it fails with

ltfs: error while loading shared libraries: libltfs.so.0: cannot open shared object file: No such file or directory

this can be fixed as described in 
http://www.tandbergdata.com/default/assets/File/PDFs/LTFS_For_Linux_and_Mac_User_Guide_March_2014.pdf
***
On some systems trying to execute the ltfs command may result in an error message of the form“libltfs.so.0: cannot open shared object file: No such file or directory”. To resolve this it is necessary to tell the linker/loader how to locate the required dynamic library files. There are several ways of doing this: 
•Add/usr/local/lib/ to the environment variable LD_LIBRARY_PATH  OR
•(Asroot) Add /usr/local/lib/  to the file /etc/ld.so.conf  and then execute /sbin/ldconfig. 
***

Maybe you could add this to the readme :)

**Comment by piste-jp-ibm** [comment]
This issue was fixed by #262.

**Comment by DrBrad** [comment]
I just cloned the repo and ran the command ltfs and I'm getting:

`ltfs: error while loading shared libraries: libltfs.so.0: cannot open shared object file: No such file or directory`

This is not in fact fixed.

**Comment by piste2750** [comment]
@DrBrad ,

> I just cloned the repo and ran the command ltfs and I'm getting:
> 
> `ltfs: error while loading shared libraries: libltfs.so.0: cannot open shared object file: No such file or directory`
> 
> This is not in fact fixed.

The problem fixed in this issue, actually #262, is the first problem, build break in the new linux systems. 

Second problem is not a target of this issue because, the solution is already provided in to the original description in this issue. Please refer the last 3 parts of the [original message](https://github.com/LinearTapeFileSystem/ltfs/issues/237#issue-787240274).

Actually, configuration of the path of dynamic loading system is different in each distro. At this time, LTFS targets RHEL7/8 mainly and they already have `user/local/lib` in it. And `gentoo` is not a list of our target list at this time. So, I don't know how to handle this kind of information in the README at all... It is really helpful if you can describe it in the README as a PR.
