### ISSUE TITLE
Deal with drive-reboots due to power line issues

### ISSUE THREAD

**Issue by andi-at-1** [LinearTapeFileSystem/ltfs#251]
**Is your feature request related to a problem? Please describe.**
I went crazy hunting for the issue which caused random drive "reboots" during operation. That only happened randomly every few weeks, but crashed some backups. I switched the cables and ports, that seems to work for a few weeks until the crashes started again. I finally found out that the power support line for the 5V line was too thin, so even the powersupply was way below its power limits (not even 50% power consumption) the drive shoots out some current  spikes, voltage dropped for a short time and lead to the drive rebooting.

When figured out i´ve bridged two power lines (of course checked if the potential is the same), now the power drops and reboots are gone.

**Describe the solution you'd like**
I think that could be a problem for more consumer-grade power supplies, so maybe the driver could detect that there is a problem and the drive went away. Dmesg reports a disconnect and reconnect of the scsi device, that could be detected and reported, and maybe clean up the driver?

**Describe alternatives you've considered**
 This issue and solution could be postet somewhere in the FAQ

**Additional context**

**Comment by piste-jp-ibm** [comment]
What kind of tape drive you are using? 

I think most of tape drive providers doesn't provide any bare drive to customer directly... Power supply to the drive is responsibility of each vendor to provide tape drive. 

> I think that could be a problem for more consumer-grade power supplies, so maybe the driver could detect that there is a problem and the drive went away. Dmesg reports a disconnect and reconnect of the scsi device, that could be detected and reported, and maybe clean up the driver?

I can't understand the request.

First of all, the LTFS is not a driver but a filesystem. Technically LTFS is just an application to use a tape drive. Because FUSE provides a functionality about filesystem driver.

Second, the LTFS already has a connection recovery logic (See https://github.com/LinearTapeFileSystem/ltfs/blob/aacc20cc5bb174f9748d4a4c336c7e2fd4a4b1cf/src/libltfs/ltfs.c#L3149). It is kicked when the LTFS receives  POR sense from the using drive (the drive returns the POR sense just after reboot). 

But there is a case that the LTSF cannot save. One case is the drive have a unwritten record on it's buffer. In this case, the LTFS make the tape read only temporary and you need to recover the tape with `ltfsck` later. But I believe you can read the files until you unmount the R/O tape. You can salvage the files if you wan to do so.

**Comment by piste-jp-ibm** [comment]
Close for a time because we don't have any response for 10 days.

Please free to reopen this with new comments.
