### ISSUE TITLE
README.md: inconsistent information about 2.4 and 2.5 spec for master branch

### ISSUE THREAD

**Issue by xosevp** [LinearTapeFileSystem/ltfs#270]
`This is the master branch of the LTFS project. At this time, this branch is used for version 2.5 development. So it wouldn't be stable a little. Please consider to follow the tree on v2.4-stable branch if you want to use stable codes.`

`At this time, the target of this project to meet is the LTFS format specifications 2.4. (https://www.snia.org/sites/default/files/technical_work/LTFS/LTFS_Format_2.4.0_TechPosition.pdf).`

And LTFS_INDEX_VERSION_STR should be updated.

**Comment by piste-jp-ibm** [comment]
In some reasons, we cannot start the development for LTFS format spec 2.5 yet actually.

I would like to the doc in this issue. But `LTFS_INDEX_VERSION_STR` shall be changed at a same time once the code for LTFS format spec 2.5 is merged.

The spec change in 2.5 related the format on the tape is only the incremental index. The version string shall be kept until the incremental index is implemented. Because current code generates the tape format meet the 2.4 format completely at this time.
