### ISSUE TITLE
When LTFS Tape Mounted - lib/udev/scsi_id return "Device or resource busy "

### ISSUE THREAD

**Issue by vguilleaume** [LinearTapeFileSystem/ltfs#303]
**Describe the bug**
We are looking forward to understand the behavior of this sequence :
- A tape is mounted successfully through LTFS binary 
- We execute the following command : /lib/udev/scsi_id --export --whitelisted /dev/sg15 --verbose

The result is "scsi_id: cannot open /dev/sg15: Device or resource busy"

**To Reproduce**
Execute the same sequence

**Expected behavior**
With Quantum - HPE - ... LTFS "driver", the behavior is to return the SCSI information related to this device : 
Example : 
ID_SCSI=1
ID_VENDOR=HP
ID_VENDOR_ENC=HP\x20\x20\x20\x20\x20\x20
ID_MODEL=Ultrium_8-SCSI
ID_MODEL_ENC=Ultrium\x208-SCSI\x20\x20
ID_REVISION=HB91
ID_TYPE=tape
ID_SERIAL=1HP_Ultrium_8-SCSI_C0F9000105
ID_SERIAL_SHORT=HP_Ultrium_8-SCSI_C0F9000105
ID_SCSI_SERIAL=C0F9000105

**Linux:**
 - OS: Centos 7.9

**Comment by piste-jp-ibm** [comment]
I think it is as designed because LTFS opens the device file exclusively to avoid unexpected operations from other processes. As a result, other applications get `EBUSY` against `open()`.

https://github.com/LinearTapeFileSystem/ltfs/blob/0fae6d816c353cf82e2eecf7970649627ebcb21c/src/tape_drivers/linux/sg/sg_tape.c#L432-L463

**Comment by vguilleaume** [comment]
Thanks Abe for the feedback and answer, this makes sens, i had something like this in mind. Thanks for the confirmation.

We will work in our side to manage this properly.
