### ISSUE TITLE
mkltfs does not work properly

### ISSUE THREAD

**Issue by misc2012-DE** [LinearTapeFileSystem/ltfs#38]
# Description
mkltfs -d /dev/st0 always leads to the following error message, 
LTFS11261E Cannot load plugin: /usr/local/lib/ltfs/libdriver-ltotape.so: undefined symbol: fuse_opt_parse
Mount, copy Data to Tape, Restore Data from Tape, unmount is possible without any issues. (Tape was already formated via ltfs in another pc)

# Environment

* OS:              Linux
* Distribution:    Ubuntu 16.04.4 LTS
* Architecture:    x86_64
* Additional info: -

# How to recreate

-

**Comment by piste-jp-ibm** [comment]
Thank you for opening the issue.

I think we and IBM never provide the tape backend module "libdriver-ltotape.so". Did you try the code on this repository?

First of all, could you clarify the version of LTFS you are facing this problem?

**Comment by misc2012-DE** [comment]
Hello,

sorry i mixed up some error messages, this is the actual error i get , when i use the current source from this git
LTFS11261E Cannot load plug-in: /usr/local/lib/ltfs/libtape-sg-ibmtape.so: undefined symbol: fuse_opt_parse.
LTFS15008E Cannot open backend 'sg'.

**Comment by piste-jp-ibm** [comment]
Hi, Thank you for your clarification.

I made a confirmation on my bench, "Ubuntu 16.04.03 xenial". It seems that mkltfs and ltfsck don't link libfuse dynamically on that machine. It is linked in RHEL or CentOS. I don't know what the difference of that at this time.

Could you use the following patch for the time being? I can load libtape-sg-ibmtape.so correctly on my bench. But I need to test this patch doesn't create any side effects on other platforms. 

```
diff --git a/src/tape_drivers/linux/sg-ibmtape/Makefile.am b/src/tape_drivers/linux/sg-ibmtape/Makefile.am
index fe9d00c..6543bbc 100644
--- a/src/tape_drivers/linux/sg-ibmtape/Makefile.am
+++ b/src/tape_drivers/linux/sg-ibmtape/Makefile.am
@@ -41,7 +41,7 @@ AM_LIBTOOLFLAGS = --tag=disable-static
 libtape_sg_ibmtape_la_SOURCES = sg_scsi_tape.c sg_ibmtape.c ibm_tape.c
 libtape_sg_ibmtape_la_DEPENDENCIES = ../../../../messages/tape_linux_sg_ibmtape_dat.o ./libtape_sg_ibmtape_la-reed_solomon_crc.lo ./libtape_sg_ibmtape_la-crc32c_crc.lo
 libtape_sg_ibmtape_la_LIBADD = ../../../../messages/tape_linux_sg_ibmtape_dat.o ./libtape_sg_ibmtape_la-reed_solomon_crc.lo ./libtape_sg_ibmtape_la-crc32c_crc.lo
-libtape_sg_ibmtape_la_LDFLAGS = -avoid-version -module
+libtape_sg_ibmtape_la_LDFLAGS = -avoid-version -module -lfuse
 libtape_sg_ibmtape_la_CPPFLAGS = @AM_CPPFLAGS@ -I ../../.. -I ../..

 ibm_tape.c:
```

**Comment by misc2012-DE** [comment]
Hello,

thanks for having a look at this issue. Since i am not a  professional, how do i apply this patch ? Thanks in advance

**Comment by piste2750** [comment]
That's the good news that your problem was solved. I will fix this problem in next few days with test on other platforms.

You can use a patch like following process. 

1. Create a text file, like `dynamic_link.patch`, which has a text from `diff` to `ibm_tape.c:` in my previous comment
2. Goto the top directory of your local repository
3. Apply the patch using `patch` command like `patch -p1 < dynamic_link.patch`

**Comment by piste-jp-ibm** [comment]
It's a good news that the problem was gone on your environment! I will commit the fix after checking this patch causes another problem on other platforms in a few days.

Following is general info to patch the code.

1. Create a text file like `dynamic-link.patch` which has the patch, from `diff -` to ` ibm_tape.c:` in my previous comment
2. Go  to the top directory of the repository
3. Apply patch using `patch` command like `patch -p1 < dynamic-link.patch`

**Comment by piste-jp-ibm** [comment]
Hi @lucasvr,

Do you know anything about this topic?

On RHEL7/CentOS7, `-l fuse` is not required to create libtape-sg-ibmtape.so. But on Ubuntu16, it seems to be required. In my understanding, `-l fuse` is not required because libtape-sg-ibmtape.so is loaded from libltfs.so and libltfs.so links libfuse.so. 

I believe the dynamic linker behavior is different from RHEL and Ubuntu. Do you have any knowledge about this difference ?

**Comment by lucasvr** [comment]
Just to report the findings that @piste-jp-ibm and I made on this topic:

Ubuntu recently decided to enable `--as-needed` by default. What that flag does is to attempt to prune dependencies added to LDFLAGS but not actually used by the executable. 

The thing is, we link `mkltfs` to `libfuse`, but `mkltfs` itself does not use any function from that library. Rather, what happens is that `libtape-sg-ibmtape.so`, a loadable "plugin", attempts to use a function from the FUSE library called `fuse_opt_parse`. Since Ubuntu's linker pruned `libfuse` from `mkltfs`, we now get an error when the plugin is loaded, since neither that plugin nor `mkltfs` have that symbol anymore.

I see two options to fix this problem. The first is to link `mkltfs` with `-Wl,--no-as-needed` to prevent the linker from stripping down the dependencies. The second is to apply the patch @piste-jp-ibm posted above. That guarantees that the actual user of the library links to it. That approach will work regardless of the linker flags present at build time.

**Comment by drnet-at** [comment]
There is ofcourse a no-patch-needed version (which is what we use on Ubuntu): export LIBS="-lfuse" ; ./configure ; make
