### ISSUE TITLE
Unsupported drive Quantum Ultrium 5

### ISSUE THREAD

**Issue by RlckAstley** [LinearTapeFileSystem/ltfs#421]
Hi, my quantum is a half size so I don't understand why it says it's unsupported. Built with mmaster and stable.

**Comment by piste-jp-ibm** [comment]
It looks some devices are supported. See the codes on `master` and `v2.4-stable`.

I'm not sure what happened on your environment because there is no failure log at all. Please put your log on start `ltfs` command.

---
Support table on master below.

https://github.com/LinearTapeFileSystem/ltfs/blob/a7916bf0b8d7264117341a5bcd06fb32a5c160f8/src/tape_drivers/quantum_tape.c#L65-L73.

**Comment by RlckAstley** [comment]
hey bro sorry for delay on this, will do but need a little more time

**Comment by piste-jp-ibm** [comment]
Close this for now. Because no update was made from 8/14.
